FROM node:alpine
WORKDIR /usr/app
COPY ./package.json .
RUN npm install
COPY . .

RUN apk add --no-cache tzdata
ENV TZ America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

CMD [ "npm", "run", "dev" ]